"""empty message

Revision ID: babf709a1377
Revises:
Create Date: 2025-03-12 18:34:29.410413

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "babf709a1377"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "moderation_tasks",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("assigned_admin", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expiration", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "content_type",
            sa.Enum("MEETUP", "POST", "MEETUP_REVIEW", name="contenttype"),
            nullable=False,
        ),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="moderationdecision"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_table(
        "outbox",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("message_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outbox")
    op.drop_table("moderation_tasks")
    # ### end Alembic commands ###
